# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "clean")
  build_android_app(task: "assemble",
                    flavor: "Live",
                    build_type: "Debug",
                    properties: {
                      "vCode" => number_of_commits,
                      "vName" => last_git_tag
                     })

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: ENV["CRASHLYTICS_API_TOKEN"],
    build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
    emails: ["developers", "android-testers"]
  )

end
