# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :android

private_lane :build do |options|
  # build the debug/live variant
  build_android_app(task: "clean")
  build_android_app(task: "assemble",
                    flavor: "Live",
                    build_type: "Debug",
                    properties: {
                      "vCode" => number_of_commits,
                      "vName" => last_git_tag
                     })
end

lane :alpha do |options|
  build(options)

  # upload to Crashlytics
  crashlytics(
    api_token: ENV["CRASHLYTICS_API_TOKEN"],
    build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
    groups: ["developers"]
  )
end

lane :beta do |options|
  build(options)

  # upload to Crashlytics
  crashlytics(
    api_token: ENV["CRASHLYTICS_API_TOKEN"],
    build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
    groups: ["developers", "android-testers"]
  )

end

lane :release do |options|
  if options[:version_name] && options[:version_code]
    puts "vName=#{options[:version_name]}, vCode=#{options[:version_code]}"

    add_git_tag(tag: options[:version_name])

    # build the debug/live variant
    build_android_app(task: "clean")
    build_android_app(task: "assemble",
                      flavor: "Live",
                      build_type: "Release",
                      properties: {
                        "vCode" => options[:version_code],
                        "vName" => options[:version_name]
                       })
  else
    puts "Invalid command, use: fastlane release version_name:x.x.x version_code:0x0x0x"
  end
end
